defaults:
  - _self_
  - data: thats

paths:
  reports: reports
  figures: ${..paths.reports}/figures
  models: models

train:
  epochs: 50
  seed: 42

  batch_size: 64
  val_size: 0.1
  test_size: 0.2


  fast_dev_run: false
  overfit_batches: 0
  schedule_lr: true
  compile: true
  debug: false

  wandb: true
  wandb_project: activity-graphs
  wandb_entity: luca-bataillard-ucl-university-college-london

  loss:
    type: bpr
    n_pairs: 128
    neg_sampler: uniform
    is_near_threshold: 5
